import 'yoga_action.dart';

class AvailableYogaActions {
  static final Map<String, YogaAction> actions = {
    'allFoursPose': YogaAction(
      id: 'allFoursPose',
      name: 'All-Fours Pose',
      text: 'Kneel on all fours and make the back straight ...',
      defaultDuration: 13,
      image: 'images/yogaActions/allFours.jpg',
      sound: 'sounds/yogaActions/allFoursPose.mp3',
    ),
    'armsOverhead': YogaAction(
      id: 'armsOverhead',
      name: 'Arms Overhead',
      text: 'Stand tall with your feet hip-width apart...',
      defaultDuration: 13,
      image: 'images/yogaActions/armsOverhead.jpg',
      sound: 'sounds/yogaActions/armsOverhead.mp3',
    ),
    'boatPose': YogaAction(
      id: 'boatPose',
      name: 'Boat Pose',
      text: 'Sit on the floor with your knees bent...',
      defaultDuration: 4,
      image: 'images/yogaActions/boat.jpg',
      sound: 'sounds/yogaActions/boatPose.mp3',
    ),
    'bridgePose': YogaAction(
      id: 'bridgePose',
      name: 'Bridge Pose',
      text: 'Lie on your back with your knees bent...',
      defaultDuration: 5,
      image: 'images/yogaActions/bridge.jpg',
      sound: 'sounds/yogaActions/bridgePose.mp3',
    ),
    'camelPose': YogaAction(
      id: 'camelPose',
      name: 'Camel Pose',
      text: 'Kneel on the floor and place your...',
      defaultDuration: 6,
      image: 'images/yogaActions/camel.jpg',
      sound: 'sounds/yogaActions/camelPose.mp3',
    ),
    'chairPose': YogaAction(
      id: 'chairPose',
      name: 'Chair Pose',
      text: 'Stand tall with your feet together...',
      defaultDuration: 4,
      image: 'images/yogaActions/chair.jpg',
      sound: 'sounds/yogaActions/chairPose.mp3',
    ),
    'childsPose': YogaAction(
      id: 'childsPose',
      name: 'Child\'s Pose',
      text: 'Sit back on your heels and rest your...',
      defaultDuration: 16,
      image: 'images/yogaActions/childs.jpg',
      sound: 'sounds/yogaActions/childsPose.mp3',
    ),
    'cobraPose': YogaAction(
      id: 'cobraPose',
      name: 'Cobra Pose',
      text: 'Lie face down and place your hands...',
      defaultDuration: 16,
      image: 'images/yogaActions/cobra.jpg',
      sound: 'sounds/yogaActions/cobraPose.mp3',
    ),
    'cooldown': YogaAction(
      id: 'cooldown',
      name: 'Cooldown',
      text: 'Namaste - Bring your hands to your heart, lower your gaze. Give yourself a smile and thank yourself for taking the time.',
      defaultDuration: 10,
      image: 'images/yogaActions/cooldown.jpg',
      sound: 'sounds/yogaActions/cooldown.mp3',
    ),
    "corpsePose": YogaAction(
      id: "corpsePose",
      name: 'Corpse Pose',
      text: 'Lie flat on your back with your legs...',
      defaultDuration: 13,
      image: 'images/yogaActions/corpse.jpg',
      sound: 'sounds/yogaActions/corpsePose.mp3',
    ),
    'deepLungeLeft': YogaAction(
      id: 'deepLungeLeft',
      name: 'Deep Lunge to the Left',
      text: 'Start in a standing position...',
      defaultDuration: 17,
      image: 'images/yogaActions/deepLunge.jpg',
      sound: 'sounds/yogaActions/deepLungeLeft.mp3',
    ),
    'deepLungeRight': YogaAction(
      id: 'deepLungeRight',
      name: 'Deep Lunge to the Right',
      text: 'Start in a standing position...',
      defaultDuration: 17,
      image: 'images/yogaActions/deepLunge.jpg',
      sound: 'sounds/yogaActions/deepLungeRight.mp3',
    ),
    'downwardFacingDog': YogaAction(
      id: 'downwardFacingDog',
      name: 'Downward Facing Dog',
      text: 'Start on your hands and knees...',
      defaultDuration: 13,
      image: 'images/yogaActions/downwardFacingDog.jpg',
      sound: 'sounds/yogaActions/downwardFacingDog.mp3',
    ),
    'extendedTrianglePose': YogaAction(
      id: 'extendedTrianglePose',
      name: 'Extended Triangle Pose',
      text: 'Stand with your feet wide apart...',
      defaultDuration: 5,
      image: 'images/yogaActions/triangle.jpg',
      sound: 'sounds/yogaActions/extendedTrianglePose.mp3',
    ),
    "kneesToChest": YogaAction(
      id: "kneesToChest",
      name: 'Knees to Chest',
      text: 'Lie on your back and hug your knees...',
      defaultDuration: 20,
      image: 'images/yogaActions/kneesToChest.jpg',
      sound: 'sounds/yogaActions/kneesToTheChest.mp3',
    ),
    'morningStretch': YogaAction(
      id: 'morningStretch',
      name: 'Morning Stretch',
      text: 'Start your day with gentle stretches...',
      defaultDuration: 10,
      image: 'images/yogaActions/morningStretch.jpg',
      sound: 'sounds/yogaActions/morningStretch.mp3',
    ),
    'mountainPose': YogaAction(
      id: 'mountainPose',
      name: 'Mountain Pose',
      text: 'Stand tall with your feet together and...',
      defaultDuration: 5,
      image: 'images/yogaActions/mountain.jpg',
      sound: 'sounds/yogaActions/mountainPose.mp3',
    ),
    'peacefulWarriorLeft': YogaAction(
      id: 'peacefulWarriorLeft',
      name: 'Peaceful Warrior Left',
      text: 'Start in a standing position...',
      defaultDuration: 10,
      image: 'images/yogaActions/peacefulWarrior.jpg',
      sound: 'sounds/yogaActions/peacefulWarriorLeft.mp3',
    ),
    'peacefulWarriorRight': YogaAction(
      id: 'peacefulWarriorRight',
      name: 'Peaceful Warrior Right',
      text: 'Start in a standing position...',
      defaultDuration: 10,
      image: 'images/yogaActions/peacefulWarrior.jpg',
      sound: 'sounds/yogaActions/peacefulWarriorRight.mp3',
    ),
    'pigeonPoseLeft': YogaAction(
      id: 'pigeonPoseLeft',
      name: 'Pigeon Pose left leg in front',
      text: 'Start in a high plank position and...',
      defaultDuration: 15,
      image: 'images/yogaActions/todo.jpg',
      sound: 'sounds/yogaActions/pigeonPoseLeft.mp3',
    ),
    'pigeonPoseRight': YogaAction(
      id: 'pigeonPoseRight',
      name: 'Pigeon Pose right leg in front',
      text: 'Start in a high plank position and...',
      defaultDuration: 15,
      image: 'images/yogaActions/todo.jpg',
      sound: 'sounds/yogaActions/pigeonPoseRight.mp3',
    ),
    'plankPose': YogaAction(
      id: 'plankPose',
      name: 'Plank Pose',
      text: 'Start in a high push-up position...',
      defaultDuration: 16,
      image: 'images/yogaActions/plank.jpg',
      sound: 'sounds/yogaActions/plankPose.mp3',
    ),
    'prepareYourself': YogaAction(
      id: 'prepareYourself',
      name: 'Prepare yourself',
      text: 'make yourself comfortable and prepare yourself...',
      defaultDuration: 10,
      image: 'images/yogaActions/prepare.jpg',
      sound: 'sounds/yogaActions/prepareYourself.mp3',
    ),
    'seatedForwardBend': YogaAction(
      id: 'seatedForwardBend',
      name: 'Seated Forward Bend',
      text: 'Sit on the floor with your legs...',
      defaultDuration: 5,
      image: 'images/yogaActions/todo.jpg',
      sound: 'sounds/yogaActions/seated_forward_bend_sound.mp3',
    ),
    'seatedTwistLeft': YogaAction(
      id: 'seatedTwistLeft',
      name: 'Seated Twist to the Left',
      text: 'Sit on the floor with your legs extended...',
      defaultDuration: 20,
      image: 'images/yogaActions/seatedTwist.jpg',
      sound: 'sounds/yogaActions/seatedTwistLeft.mp3',
    ),
    'seatedTwistRight': YogaAction(
      id: 'seatedTwistRight',
      name: 'Seated Twist to the Right',
      text: 'Sit on the floor with your legs extended...',
      defaultDuration: 20,
      image: 'images/yogaActions/seatedTwist.jpg',
      sound: 'sounds/yogaActions/seatedTwistRight.mp3',
    ),
    'simpleSit': YogaAction(
      id: 'simpleSit',
      name: 'Simple Sit',
      text: 'Sit on the floor with your legs crossed...',
      defaultDuration: 20,
      image: 'images/yogaActions/simpleSit.jpg',
      sound: 'sounds/yogaActions/simpleSit.mp3',
    ),
    'standingForwardBend': YogaAction(
      id: 'standingForwardBend',
      name: 'Standing Forward Bend',
      text: 'Stand tall with your feet together and...',
      defaultDuration: 15,
      image: 'images/yogaActions/standigForwardBend.jpg',
      sound: 'sounds/yogaActions/standigForwardBend.mp3',
    ),
    'supineKneeBendLeft': YogaAction(
      id: 'supineKneeBendLeft',
      name: 'Supine Knee Bend Left',
      text: 'Lie on your back with your knees bent...',
      defaultDuration: 16,
      image: 'images/yogaActions/supineKneeBend.jpg',
      sound: 'sounds/yogaActions/supineKneeBendLeft.mp3',
    ),
    'supineKneeBendRight': YogaAction(
      id: 'supineKneeBendRight',
      name: 'Supine Knee Bend',
      text: 'Lie on your back with your knees bent...',
      defaultDuration: 16,
      image: 'images/yogaActions/supineKneeBend.jpg',
      sound: 'sounds/yogaActions/supineKneeBendRight.mp3',
    ),
    'treePose': YogaAction(
      id: 'treePose',
      name: 'Tree Pose',
      text: 'Stand tall and shift your weight onto...',
      defaultDuration: 4,
      image: 'images/yogaActions/tree.jpg',
      sound: 'sounds/yogaActions/treePose.mp3',
    ),
    'warrior1Left': YogaAction(
      id: 'warrior1Left',
      name: 'Warrior I Pose Left',
      text: 'Step your left foot back and...',
      defaultDuration: 10,
      image: 'images/yogaActions/warrior1.jpg',
      sound: 'sounds/yogaActions/warrior1Left.mp3',
    ),
    'warrior1Right': YogaAction(
      id: 'warrior1Right',
      name: 'Warrior I Pose Right',
      text: 'Step your left foot back and...',
      defaultDuration: 10,
      image: 'images/yogaActions/warrior1.jpg',
      sound: 'sounds/yogaActions/warrior1Right.mp3',
    ),
    'standingHalfForwardBend': YogaAction(
      id: 'standingHalfForwardBend',
      name: 'Standing Half Forward Bend',
      text: 'Stand tall with your feet together and...',
      defaultDuration: 15,
      image: 'images/yogaActions/todo.jpg',
      sound: 'sounds/yogaActions/todo.mp3',
    ),
    'warrior2Left': YogaAction(
      id: 'warrior2Left',
      name: 'Warrior 2 Left',
      text: 'Start in a standing position...',
      defaultDuration: 20,
      image: 'images/yogaActions/warrior2.jpg',
      sound: 'sounds/yogaActions/warrior2Left.mp3',
    ),
    'warrior2Right': YogaAction(
      id: 'warrior2Right',
      name: 'Warrior 2 Right',
      text: 'Start in a standing position...',
      defaultDuration: 20,
      image: 'images/yogaActions/warrior2.jpg',
      sound: 'sounds/yogaActions/warrior2Right.mp3',
    ),
  };

  static YogaAction getAction(String actionId) {
    var yogaActionNotFoundFallback = YogaAction(
      id: actionId,
      name: "$actionId is not yet implemented. Or it is the wrong actionId. Contact the developer",
      text: '$actionId is not yet implemented. Or it is the wrong actionId. Contact the developer',
      defaultDuration: 10,
      image: 'images/yogaActions/default.jpg',
      sound: 'sounds/yogaActions/default.mp3',
    );
    return actions[actionId] ?? yogaActionNotFoundFallback;
  }

  // Get default duration of a YogaAction by ID
  static int getDefaultActionDuration(String id) {
    final YogaAction? action = actions[id];
    var defaultDurationFallback = 10;
    return action?.defaultDuration ?? defaultDurationFallback;
  }
}
