import 'yoga_action.dart';

class AvailableYogaActions {
  static final Map<String, YogaAction> actions = {
    'allFoursPose': YogaAction(
      id: 'allFoursPose',
      name: 'All-Fours Pose',
      text: 'Kneel on all fours and make the back straight ...',
      defaultDuration: 13,
      image: 'images/allFours.jpg',
      sound: 'sounds/allFoursPose.mp3',
    ),
    'armsOverhead': YogaAction(
      id: 'armsOverhead',
      name: 'Arms Overhead',
      text: 'Stand tall with your feet hip-width apart...',
      defaultDuration: 13,
      image: 'images/armsOverhead.jpg',
      sound: 'sounds/armsOverhead.mp3',
    ),
    'boatPose': YogaAction(
      id: 'boatPose',
      name: 'Boat Pose',
      text: 'Sit on the floor with your knees bent...',
      defaultDuration: 4,
      image: 'images/boat.jpg',
      sound: 'sounds/boatPose.mp3',
    ),
    'bridgePose': YogaAction(
      id: 'bridgePose',
      name: 'Bridge Pose',
      text: 'Lie on your back with your knees bent...',
      defaultDuration: 5,
      image: 'images/bridge.jpg',
      sound: 'sounds/bridgePose.mp3',
    ),
    'camelPose': YogaAction(
      id: 'camelPose',
      name: 'Camel Pose',
      text: 'Kneel on the floor and place your...',
      defaultDuration: 6,
      image: 'images/camel.jpg',
      sound: 'sounds/camelPose.mp3',
    ),
    'chairPose': YogaAction(
      id: 'chairPose',
      name: 'Chair Pose',
      text: 'Stand tall with your feet together...',
      defaultDuration: 4,
      image: 'images/chair.jpg',
      sound: 'sounds/chairPose.mp3',
    ),
    'childsPose': YogaAction(
      id: 'childsPose',
      name: 'Child\'s Pose',
      text: 'Sit back on your heels and rest your...',
      defaultDuration: 16,
      image: 'images/childs.jpg',
      sound: 'sounds/childsPose.mp3',
    ),
    'cobraPose': YogaAction(
      id: 'cobraPose',
      name: 'Cobra Pose',
      text: 'Lie face down and place your hands...',
      defaultDuration: 16,
      image: 'images/cobra.jpg',
      sound: 'sounds/cobraPose.mp3',
    ),
    'cooldown': YogaAction(
      id: 'cooldown',
      name: 'Cooldown',
      text: 'Namaste - Bring your hands to your heart, lower your gaze. Give yourself a smile and thank yourself for taking the time.',
      defaultDuration: 10,
      image: 'images/cooldown.jpg',
      sound: 'sounds/cooldown.mp3',
    ),
    "corpsePose": YogaAction(
      id: "corpsePose",
      name: 'Corpse Pose',
      text: 'Lie flat on your back with your legs...',
      defaultDuration: 13,
      image: 'images/corpse.jpg',
      sound: 'sounds/corpsePose.mp3',
    ),
    'deepLungeLeft': YogaAction(
      id: 'deepLungeLeft',
      name: 'Deep Lunge to the Left',
      text: 'Start in a standing position...',
      defaultDuration: 17,
      image: 'images/deepLunge.jpg',
      sound: 'sounds/deepLungeLeft.mp3',
    ),
    'deepLungeRight': YogaAction(
      id: 'deepLungeRight',
      name: 'Deep Lunge to the Right',
      text: 'Start in a standing position...',
      defaultDuration: 17,
      image: 'images/deepLunge.jpg',
      sound: 'sounds/deepLungeRight.mp3',
    ),
    'downwardFacingDog': YogaAction(
      id: 'downwardFacingDog',
      name: 'Downward Facing Dog',
      text: 'Start on your hands and knees...',
      defaultDuration: 13,
      image: 'images/downwardFacingDog.jpg',
      sound: 'sounds/downwardFacingDog.mp3',
    ),
    'extendedTrianglePose': YogaAction(
      id: 'extendedTrianglePose',
      name: 'Extended Triangle Pose',
      text: 'Stand with your feet wide apart...',
      defaultDuration: 5,
      image: 'images/triangle.jpg',
      sound: 'sounds/extendedTrianglePose.mp3',
    ),
    "kneesToChest": YogaAction(
      id: "kneesToChest",
      name: 'Knees to Chest',
      text: 'Lie on your back and hug your knees...',
      defaultDuration: 20,
      image: 'images/kneesToChest.jpg',
      sound: 'sounds/kneesToTheChest.mp3',
    ),
    'morningStretch': YogaAction(
      id: 'morningStretch',
      name: 'Morning Stretch',
      text: 'Start your day with gentle stretches...',
      defaultDuration: 10,
      image: 'images/morningStretch.jpg',
      sound: 'sounds/morningStretch.mp3',
    ),
    'mountainPose': YogaAction(
      id: 'mountainPose',
      name: 'Mountain Pose',
      text: 'Stand tall with your feet together and...',
      defaultDuration: 5,
      image: 'images/mountain.jpg',
      sound: 'sounds/mountainPose.mp3',
    ),
    'peacefulWarriorLeft': YogaAction(
      id: 'peacefulWarriorLeft',
      name: 'Peaceful Warrior Left',
      text: 'Start in a standing position...',
      defaultDuration: 10,
      image: 'images/peacefulWarrior.jpg',
      sound: 'sounds/peacefulWarriorLeft.mp3',
    ),
    'peacefulWarriorRight': YogaAction(
      id: 'peacefulWarriorRight',
      name: 'Peaceful Warrior Right',
      text: 'Start in a standing position...',
      defaultDuration: 10,
      image: 'images/peacefulWarrior.jpg',
      sound: 'sounds/peacefulWarriorRight.mp3',
    ),
    'pigeonPoseLeft': YogaAction(
      id: 'pigeonPoseLeft',
      name: 'Pigeon Pose left leg in front',
      text: 'Start in a high plank position and...',
      defaultDuration: 15,
      image: 'images/todo.jpg',
      sound: 'sounds/pigeonPoseLeft.mp3',
    ),
    'pigeonPoseRight': YogaAction(
      id: 'pigeonPoseRight',
      name: 'Pigeon Pose right leg in front',
      text: 'Start in a high plank position and...',
      defaultDuration: 15,
      image: 'images/todo.jpg',
      sound: 'sounds/pigeonPoseRight.mp3',
    ),
    'plankPose': YogaAction(
      id: 'plankPose',
      name: 'Plank Pose',
      text: 'Start in a high push-up position...',
      defaultDuration: 16,
      image: 'images/plank.jpg',
      sound: 'sounds/plankPose.mp3',
    ),
    'prepareYourself': YogaAction(
      id: 'prepareYourself',
      name: 'Prepare yourself',
      text: 'make yourself comfortable and prepare yourself...',
      defaultDuration: 10,
      image: 'images/prepare.jpg',
      sound: 'sounds/sounds/prepareYourself.mp3',
    ),
    'seatedForwardBend': YogaAction(
      id: 'seatedForwardBend',
      name: 'Seated Forward Bend',
      text: 'Sit on the floor with your legs...',
      defaultDuration: 5,
      image: 'images/todo.jpg',
      sound: 'sounds/seated_forward_bend_sound.mp3',
    ),
    'seatedTwistLeft': YogaAction(
      id: 'seatedTwistLeft',
      name: 'Seated Twist to the Left',
      text: 'Sit on the floor with your legs extended...',
      defaultDuration: 20,
      image: 'images/seatedTwist.jpg',
      sound: 'sounds/seatedTwistLeft.mp3',
    ),
    'seatedTwistRight': YogaAction(
      id: 'seatedTwistRight',
      name: 'Seated Twist to the Right',
      text: 'Sit on the floor with your legs extended...',
      defaultDuration: 20,
      image: 'images/seatedTwist.jpg',
      sound: 'sounds/seatedTwistRight.mp3',
    ),
    'simpleSit': YogaAction(
      id: 'simpleSit',
      name: 'Simple Sit',
      text: 'Sit on the floor with your legs crossed...',
      defaultDuration: 20,
      image: 'images/simpleSit.jpg',
      sound: 'sounds/sounds/simpleSit.mp3',
    ),
    'standingForwardBend': YogaAction(
      id: 'standingForwardBend',
      name: 'Standing Forward Bend',
      text: 'Stand tall with your feet together and...',
      defaultDuration: 15,
      image: 'images/todo.jpg',
      sound: 'sounds/standing_forward_bend_sound.mp3',
    ),
    'supineKneeBendLeft': YogaAction(
      id: 'supineKneeBendLeft',
      name: 'Supine Knee Bend Left',
      text: 'Lie on your back with your knees bent...',
      defaultDuration: 16,
      image: 'images/supineKneeBend.jpg',
      sound: 'sounds/supineKneeBendLeft.mp3',
    ),
    'supineKneeBendRight': YogaAction(
      id: 'supineKneeBendRight',
      name: 'Supine Knee Bend',
      text: 'Lie on your back with your knees bent...',
      defaultDuration: 16,
      image: 'images/supineKneeBend.jpg',
      sound: 'sounds/supineKneeBendRight.mp3',
    ),
    'treePose': YogaAction(
      id: 'treePose',
      name: 'Tree Pose',
      text: 'Stand tall and shift your weight onto...',
      defaultDuration: 4,
      image: 'images/tree.jpg',
      sound: 'sounds/treePose.mp3',
    ),
    'warrior1Left': YogaAction(
      id: 'warrior1Left',
      name: 'Warrior I Pose Left',
      text: 'Step your left foot back and...',
      defaultDuration: 10,
      image: 'images/warrior1.jpg',
      sound: 'sounds/warrior1Left.mp3',
    ),
    'warrior1Right': YogaAction(
      id: 'warrior1Right',
      name: 'Warrior I Pose Right',
      text: 'Step your left foot back and...',
      defaultDuration: 10,
      image: 'images/warrior1.jpg',
      sound: 'sounds/warrior1Right.mp3',
    ),
    'standingHalfForwardBend': YogaAction(
      id: 'standingHalfForwardBend',
      name: 'Standing Half Forward Bend',
      text: 'Stand tall with your feet together and...',
      defaultDuration: 15,
      image: 'images/todo.jpg',
      sound: 'sounds/todo.mp3',
    ),
    'warrior2Left': YogaAction(
      id: 'warrior2Left',
      name: 'Warrior 2 Left',
      text: 'Start in a standing position...',
      defaultDuration: 20,
      image: 'images/warrior2.jpg',
      sound: 'sounds/warrior2Left.mp3',
    ),
    'warrior2Right': YogaAction(
      id: 'warrior2Right',
      name: 'Warrior 2 Right',
      text: 'Start in a standing position...',
      defaultDuration: 20,
      image: 'images/warrior2.jpg',
      sound: 'sounds/warrior2Right.mp3',
    ),
  };

  static YogaAction getAction(String actionId) {
    var yogaActionNotFoundFallback = YogaAction(
      id: actionId,
      name: "$actionId is not yet implemented. Contact the developer",
      text: '$actionId is not yet implemented. Contact the developer',
      defaultDuration: 10,
      image: 'images/default.jpg',
      sound: 'sounds/sounds/default.mp3',
    );
    return actions[actionId] ?? yogaActionNotFoundFallback;
  }

  // Get default duration of a YogaAction by ID
  static int getDefaultActionDuration(String id) {
    final YogaAction? action = actions[id];
    var defaultDurationFallback = 10;
    return action?.defaultDuration ?? defaultDurationFallback;
  }
}
